after-school-garbage-squad/repaint-server

.github/workflows/audit.yml, .github/workflows/ci.yml, migration/src/lib.rs
=> ci: add security audit ci and, main workflow

Cargo.lock, Cargo.toml, Justfile, migration/src/m20230712_215023_create_visitor_table.rs, model/Cargo.toml, model/src/admin.rs, model/src/event.rs, model/src/event_beacon.rs, model/src/event_image.rs, model/src/event_spot.rs, model/src/id.rs, model/src/lib.rs, model/src/visitor.rs, model/src/visitor_image.rs, model/src/visitor_palette.rs
=> feat: implement model

.env, docker-compose.yml, env_injection.sh, grafana/Dockerfile, grafana/datasources/psql.yml
Docker Imageが環境変数を注入し、Grafanaを自動的に構成するように変更しました。
これにより、docker compose経由でDocker Imageにargsが注入されるので、`.env`を編集することで依存関係を構成できます。
=> feat(grafana): Integrating grafana into docker compose

usecase/src/model.rs, usecase/src/model/spot.rs, usecase/src/model/traffic.rs, usecase/src/usecase.rs, usecase/src/usecase/admin.rs, usecase/src/usecase/event.rs, usecase/src/usecase/image.rs, usecase/src/usecase/palette.rs, usecase/src/usecase/spot.rs, usecase/src/usecase/traffic.rs, usecase/src/usecase/visitor.rs
=> refactor: refactor usecase

.dockerignore, Dockerfile
=> build: add Dockerfile for deploy

Cargo.lock, Cargo.toml, gcs/Cargo.toml, gcs/src/lib.rs, usecase/src/infra.rs, usecase/src/infra/gcs.rs, usecase/src/usecase/image.rs
=> feat: impl GCS client

Cargo.lock, fcm/Cargo.toml, fcm/src/lib.rs
=> feat: impl authorization for fcm

Cargo.lock, Cargo.toml, fcm/src/lib.rs, otp/Cargo.toml, otp/src/lib.rs, usecase/src/infra.rs, usecase/src/infra/otp.rs, usecase/src/model.rs, usecase/src/model/otp.rs
=> feat: impl image otp client

Cargo.lock, Cargo.toml, pubsub/Cargo.toml, pubsub/src/lib.rs, usecase/src/infra.rs, usecase/src/infra/pubsub.rs
=> feat: impl pubsub

.github/CODEOWNERS, api/src/lib.rs, pubsub/src/lib.rs, usecase/src/infra/pubsub.rs, usecase/src/usecase/image.rs, usecase/src/usecase/palette.rs
=> feat: impl merge publish

core/src/impls/image.rs, usecase/src/infra/repo.rs, usecase/src/usecase/image.rs, usecase/src/usecase/palette.rs, usecase/src/usecase/visitor.rs
=> fix: make Option return

.github/workflows/emergency.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, api/Cargo.toml, api/src/lib.rs, src/main.rs
=> feat: impl sentry

core/patch/entity.patch, core/src/entity/event_spots.rs, core/src/entity/visitor_images.rs, core/src/impls/event.rs, core/src/impls/image.rs, core/src/impls/spot.rs, core/src/lib.rs, firestore/src/lib.rs, migration/src/m20230712_213646_create_event_spot_table.rs, migration/src/m20230712_215554_create_visitor_image_table.rs, sg/src/lib.rs, usecase/src/infra/repo.rs, usecase/src/usecase/event.rs, usecase/src/usecase/image.rs, usecase/src/usecase/palette.rs, usecase/src/usecase/spot.rs, usecase/src/usecase/visitor.rs
=> feat: impl set and check image update flag

Dockerfile, api/src/routes/admin/event/image.rs, api/src/routes/visitor/image.rs, otp/src/lib.rs, usecase/src/infra/otp.rs, usecase/src/model/image.rs, usecase/src/usecase/image.rs
=> feat: impl image proxy for event image

firestore/src/lib.rs, firestore/src/structure.rs
=> refactor: remove some field in structure

Cargo.lock, api/src/routes/admin/event/traffic.rs, firestore/src/lib.rs, firestore/src/structure.rs, usecase/Cargo.toml, usecase/src/infra/firestore.rs, usecase/src/model/traffic.rs, usecase/src/usecase/palette.rs, usecase/src/usecase/traffic.rs
=> feat: update traffic logic

api/src/routes/admin/event/image.rs, core/patch/entity.patch, core/src/entity/event_spots.rs, core/src/entity/visitor_images.rs, core/src/impls/image.rs, core/src/impls/palette.rs, core/src/impls/visitor.rs, migration/src/m20230712_215554_create_visitor_image_table.rs, model/src/visitor_image.rs
=> feat: refactor visitor_images logic

firestore/src/lib.rs, firestore/src/structure.rs, usecase/src/infra/firestore.rs, usecase/src/usecase/spot.rs
=> fix: fix drop logic

core/src/impls/spot.rs, core/src/impls/visitor.rs, usecase/src/infra/repo.rs, usecase/src/usecase/palette.rs, usecase/src/usecase/spot.rs
=> feat: impl setting last_picked_at and last_droped_at in repository and impls

Cargo.lock, usecase/Cargo.toml, usecase/src/usecase/palette.rs
=> fix: fix pick core logic
